export const SecurityEvent = {
  HTTP_COMPLETED: 'OPS.HTTP.COMPLETED',
  HTTP_ERROR: 'OPS.HTTP.ERROR',
  LOGIN_SUCCESS: 'AUD.AUTH.LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUD.AUTH.LOGIN_FAILURE',
  THROTTLED: 'AUD.AUTH.THROTTLED',
  REFRESH_SUCCESS: 'AUD.AUTH.REFRESH_SUCCESS',
  REFRESH_FAILURE: 'AUD.AUTH.REFRESH_FAILURE',
  REFRESH_REPLAY: 'AUD.AUTH.REFRESH_REPLAY',
  LOGOUT: 'AUD.AUTH.LOGOUT',
  SESSIONS_REVOKED: 'AUD.AUTH.SESSIONS_REVOKED',
  AUTHORIZATION_FAILURE: 'AUD.AUTHZ.DENIED',
  ACCOUNT_UPDATED: 'AUD.ACCOUNT.UPDATED',
  ACCOUNT_DELETED: 'AUD.ACCOUNT.DELETED',
  SURVEY_CREATED: 'AUD.SURVEY.CREATED',
  SURVEY_UPDATED: 'AUD.SURVEY.UPDATED',
  SURVEY_DELETED: 'AUD.SURVEY.DELETED',
  REPORT_STARTED: 'AUD.REPORT.STARTED',
  REPORT_SUCCESS: 'AUD.REPORT.SUCCESS',
  REPORT_FAILURE: 'AUD.REPORT.FAILURE',
  REPORT_TIMEOUT: 'AUD.REPORT.TIMEOUT',
  REPORT_CAPACITY_REJECTED: 'AUD.REPORT.CAPACITY_REJECTED',
  RENDERER_REQUEST_BLOCKED: 'AUD.RENDERER.REQUEST_BLOCKED',
} as const

export type SecurityEventCode =
  (typeof SecurityEvent)[keyof typeof SecurityEvent]
